# 应用名称
spring:
  application:
    name: simpleblog-java
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/simpleblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 数据库用户名&密码：
    username: root
    password: 123456
  #指定freemarker的模板路径和模板的后缀
  freemarker:
    template-loader-path: classpath:/webapp/
    suffix: .ftl
    # 指定字符集
    charset: utf-8
    # 指定是否要启用缓存
    cache: false
    #指定是否要暴露请求和会话属性
    expose-request-attributes: true
    expose-session-attributes: true
  # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/static/# 应用服务 WEB 访问端口
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志


lycan:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

